FROM quay.io/ascend/cann:8.5.1-a3-ubuntu22.04-py3.11

ARG SOC_VERSION="ascend910_9391"

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm-256color
ENV PIP_ROOT_USER_ACTION=ignore
ENV PIP_CONSTRAINT=""

ENV LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/add-ons:/usr/local/Ascend/ascend-toolkit/latest/fwkacllib/lib64:/usr/local/Ascend/ascend-toolkit/latest/acllib/lib64:/usr/local/Ascend/ascend-toolkit/latest/atc/lib64:${LD_LIBRARY_PATH}
ENV ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        gcc g++ cmake libnuma-dev wget git curl jq vim \
        build-essential iproute2 openjdk-21-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

RUN pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple && \
    pip config set global.trusted-host mirrors.huaweicloud.com && \
    pip install --upgrade pip packaging setuptools && \
    pip cache purge

WORKDIR /workspace

RUN git clone --depth 1 -b v0.13.0 https://github.com/vllm-project/vllm.git && \
    git clone --depth 1 -b releases/v0.13.0 https://github.com/vllm-project/vllm-ascend.git

RUN cd vllm && \
    pip install -r requirements/build.txt && \
    VLLM_TARGET_DEVICE=empty pip install -v -e . && \
    pip uninstall -y triton && \
    pip cache purge && \
    cd ..

RUN pip install torch==2.8.0+cpu torchvision==0.23.0 torchaudio==2.8.0 \
    --index-url https://download.pytorch.org/whl/cpu

RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    cd vllm-ascend && \
    pip install -r requirements.txt && \
    SOC_VERSION=${SOC_VERSION} pip install -v -e . --extra-index-url https://download.pytorch.org/whl/cpu

WORKDIR /workspace/ROLL
COPY . .

RUN pip install -r requirements_common.txt

RUN pip install "deepspeed==0.16.4" "transformers==4.57.6" "tensorboard==2.20.0"

RUN pip install -e .

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip uninstall -y triton && \
    pip uninstall -y triton-ascend && \
    pip install triton-ascend==3.2.0 && \
    pip cache purge

RUN echo "source /usr/local/Ascend/ascend-toolkit/set_env.sh" >> /root/.bashrc && \
    echo "source /usr/local/Ascend/nnal/atb/set_env.sh" >> /root/.bashrc

CMD ["/bin/bash"]